sudo: required
services:
        - docker
before_install:
        - docker-compose build web
        - docker-compose up   -d
        - docker ps
script:
        - docker-compose run web python /code/CSUMapSite/manage.py test
