# Generated by Django 3.1.1 on 2020-12-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
                ('clubs', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ModelTest',
        ),
    ]
