# Generated by Django 3.1.1 on 2020-12-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0002_auto_20201202_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingCordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='cordinates',
            field=models.ManyToManyField(to='CSUMapApp.buildingCordinates'),
        ),
    ]
