# Generated by Django 3.1.1 on 2020-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0004_auto_20201202_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='buildingDesc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
