# Generated by Django 3.1.1 on 2020-12-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buildingCordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=50)),
                ('clubDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingName', models.CharField(max_length=100)),
                ('buildingDesc', models.TextField()),
                ('clubs', models.ManyToManyField(to='CSUMapApp.Clubs')),
                ('cordinates', models.ManyToManyField(to='CSUMapApp.buildingCordinates')),
            ],
        ),
    ]
