# Generated by Django 3.1.1 on 2020-12-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0002_auto_20201207_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clubs',
        ),
        migrations.AddField(
            model_name='building',
            name='clubs',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
