# Generated by Django 3.1.1 on 2020-12-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0003_auto_20201207_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buildingCordinates',
        ),
    ]
