# Generated by Django 3.1.1 on 2020-12-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSUMapApp', '0004_delete_buildingcordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bUrl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
